version: 0.2


phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 12
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - APPLICATION_NAME=return_order_frontend
      - APPLICATION_VERSION=latest
      - REPOSITORY_URI=156962844638.dkr.ecr.ap-south-1.amazonaws.com/ritam_return_order_frontend
  build:
    commands:
      - echo Build started on `date`
      - echo Building project...
      - npm run build
      - echo Building Docker image...
      - docker build -t $APPLICATION_NAME:$APPLICATION_VERSION .
      - docker tag $APPLICATION_NAME:$APPLICATION_VERSION $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Created docker images...
      - docker images
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"ritam_return_order_frontend_container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
